### ISSUE TITLE
Not working on private repos

### ISSUE THREAD

**Issue by hairyhenderson** [greenkeeperio/greenkeeper-postpublish#7]
When I run `greenkeeper-postpublish` for a private repo, I'm expecting some branches/PRs to be created in dependent projects (also private repos enabled for greenkeeper), but I'm not seeing anything.

The command runs without errors:

``` console
$ greenkeeper-postpublish       
🌴  info postpublish Use @myorg/mymodule@0.2.0
Announced @myorg/mymodule@0.2.0 to Greenkeeper
```

One possible glitch is that I'm not using npmjs.com to host my private modules - I'm using Artifactory Online...

**Comment by travi** [comment]
While [this response](https://twitter.com/greenkeeperio/status/791542934617358336) certainly suggests that postpublish should work with private repos, I have not seen the expected PRs created for my projects either. 

My assumption is that the problem is not with postpublish itself, but rather with the part of greenkeeper that creates the PRs. Is there anything I can do to help correct this behavior, or is that something that only the @greenkeeperio team can resolve?

**Comment by hairyhenderson** [comment]
@travi are you publishing to npmjs.com? or some other registry?

**Comment by travi** [comment]
I'm publishing to an internal Nexus server. These are scored packages as well. 

Using postpublish has been working well for public scoped packages published to npmjs.com, but not those published to our internal registry.

**Comment by hairyhenderson** [comment]
ah. I'm publishing to an artifactory registry - I wonder if there's something up with non-npmjs.com registries... Would be awesome to get a comment from the @greenkeeperio team :wink:

**Comment by travi** [comment]
at least in my case, i bet this is due to the fact that we use the new integration. the warning on the front page of this repo suggests that it doesnt work that way...

**Comment by hairyhenderson** [comment]
hrm. I'm still using the old integration.

**Comment by finnp** [comment]
Hey,

For the old Greenkeeper private repositories only work with npm. So if you host your modules somewhere else it will not work. 

For the new GitHub Integration if you enable Greenkeeper on a private repository, you will now receive a secret that you can use to set up npm hooks for the private packages on npm. So you will not need to use postpublish anymore.

However since npm hooks are not supported by other registries, this will only work with the npm private registry. But if you're interested in using third-party registries there is technically also a possibility, but that's not very usable nor documented yet.

Best,
Finn

**Comment by travi** [comment]
I'm very interested in understanding how to use greenkeeper with a third-party registry with the new github integration. How can I get information about the possibility that you mention? 

I'm also more than happy to provide feedback if this is something still being shaped and a beta user could be helpful to you.

**Comment by travi** [comment]
Also, was it always the case that the old greenkeeper did not work with third-party registries? The tweet I referenced above certainly suggests that it was expected to work. The confidence of that response helped me convince my team that we'd be very able to get the whole flow working in our environment.

**Comment by hairyhenderson** [comment]
> For the old Greenkeeper private repositories only work with npm. So if you host your modules somewhere else it will not work.

This explains a lot, but it contradicts what the documentation claimed... We're very interested in support for third-party registry support too.

**Comment by travi** [comment]
in case it is helpful to this effort, it looks like nexus does support at least some level of webhook notification: https://books.sonatype.com/nexus-book/reference3/webhooks.html

**Comment by travi** [comment]
@finnp is there any insight that you can provide us on the possibilities for third-party registries that you mentioned?

i've conditioned myself to expect dependencies to always be up to date, so i got tripped up today when one of our private packages was not. it ended up costing me a significant amount of time before i realized that the issue was simply a mismatched version.

please let me know if there is anything i can do to help third-party registry support move forward.
